name: Bug report😭
description: Report a bug or unexpected behavior
labels: ["Bug"]
assignees:
  - DavideBlade
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form accurately to improve the handling of the issue. Thanks for your time.

  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      description: Specify what tasks you completed before opening this report.
      options:
        - label: "I have read the [Wiki](https://github.com/DavideBlade/Clash-of-Minecrafters/wiki)."
          required: false
        - label: "I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/DavideBlade/Clash-of-Minecrafters/issues?q=is%3Aissue)."
          required: false
        - label: "I have tested the [latest version](https://www.spigotmc.org/resources/31180/history) of Clash of Minecrafters and the bug is still there."
          required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Describe what happened and what you expected to happen instead.
        Provide **screenshots**, **logs**, **configuration files**, and anything else that might be helpful.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Reproduction of the problem
      description: List of steps to replicate the bug.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: Server version
      description: Copy and paste the output of the `/version` command.
      placeholder: "This server is running CraftBukkit version 3475-Spigot-ffceeae-b5559f8 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: Version displayed with the `/CoM` command.
      placeholder: "3.0 alpha"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: java
