name: Bug Report😭
description: Report a bug or unexpected behavior
labels: ["bug"]
assignees:
  - DavideBlade
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form accurately to improve the handling of the issue. Thanks for your time.
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      description: Specify what tasks you completed before opening this report.
      options:
       - label: "I have read the [Wiki](https://github.com/DavideBlade/Clash-of-Minecrafters/wiki)."
         required: true
       - label: "I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/DavideBlade/Clash-of-Minecrafters/issues?q=is%3Aissue)."
         required: false
- type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what happened and what you expected to happen instead.
      placeholder: Tell us what you see!
    validations:
      required: true
- type: textarea
    id: how-to-reproduce
    attributes:
      label: Reproduction of the problem
      description: List of steps to replicate the bug.
      placeholder: |
       1.
       2.
       3.
       4.
       ...
    validations:
      required: true
  - type: input
    id: server-version
    attributes:
      label: Server version
      description: Copy and paste the output of the `/version` command
      placeholder: "This server is running CraftBukkit version 3132-Spigot-66f9d3c-40caacc (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
