name: Help request
description: Ask a question
labels: ["Help"]
assignees:
  - DavideBlade
body:
  - type: markdown
    attributes:
      value: |
        Please complete this form accurately to improve the handling of your request.

  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      description: Specify what tasks you completed before opening this request.
      options:
        - label: "I have read the [wiki](https://github.com/DavideBlade/Clash-of-Minecrafters/wiki)."
          required: false
        - label: "I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/DavideBlade/Clash-of-Minecrafters/issues?q=is%3Aissue)."
          required: false

  - type: textarea
    id: information
    attributes:
      label: Description
      description: |
        Describe what happened and what you expected to happen instead.
        Provide **screenshots**, **logs**, **configuration files**, and anything else that might be helpful
      placeholder: What are you trying to do? What have you tried so far?
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: Version displayed with the `/CoM` command.
      placeholder: "3.0 alpha"
    validations:
      required: true
