blank_issues_enabled: false
contact_links:
  - name: Community
    url: https://www.spigotmc.org/threads/190277
    about: To discuss with the community or ask general questions use the SpigotMC page
